# Ansible managed

version: "2.4"

services:

    cxi-hub:
        container_name: cxi-hub
        hostname: "QAMOJIX-HUB01"
        image: "gcr.io/mojix-registry/hub:4.1.9"
        environment:
          - tagauth_protocol=http
          - tagauth_host=sprint.vizix.cloud
          - tagauth_port=18080
          - digital_plateform_protocol=http
          - digital_plateform_host=sprint.vizix.cloud
          - digital_plateform_port=18080
          - tenant_code=BAT
          - digital_plateform_notification=sprint.vizix.cloud
          - digital_plateform_user=BATroot
          - digital_plateform_pass=m0j1xInc!
          - amqp_cloud_server_user=admin
          - amqp_cloud_server_pass=control123!
          - amqp_local_server_host=cxi-hub-rabbitmq
          - amqp_local_server_user=whiterabbit
          - amqp_local_server_pass=rabbit
          - tomcat_admin_user=tomcat
          - tomcat_admin_pass=tomcat
          - hub_configuration_local_host=cxi-hub
          - hub_configuration_local_port=8080
          - hub_apl_filtering_enable=False
          - hub_apl_filtering_companiesPrefix=
          - hub_hal_rest_server_host=cxi-hub
          - hub_hal_rest_server_port=8080
          - hub_hal_rest_server_scheme=http
          - apl_server_host=cxi-hub
          - apl_server_port=8080
          - apl_server_scheme=http
          - hal_server_host=cxi-hub
          - hal_server_port=8080
          - hal_server_scheme=http
          - http_timeout_read=5000
          - configuration_devices_api_read_timeout=5000
          - configuration_infra_api_read_timeout=5000
        ports:
          - 8080:8080
          - 8000:8000
        volumes:
          - /data/hub/tomcat/conf_replay:/usr/local/tomcat/tagsys_replay:ro
          - /data/hub/tomcat/logs:/usr/local/tomcat/logs
          - /data/hub/tomcat/www:/usr/local/tomcat/www
          - /data/hub/tomcat/tagsys:/usr/local/tomcat/tagsys
          - /data/hub/tomcat/hub_data:/usr/local/tomcat/hub_data
          - /data/hub/heartbeat/conf:/usr/share/heartbeat/conf
          - /data/hub/tomcat/webapps_custom/war:/usr/local/tomcat/webapps_custom/war
          - /data/hub/tomcat/webapps_custom/resources:/usr/local/tomcat/webapps_custom/resources
        extra_hosts:
          - "sprint.vizix.cloud:10.128.0.64"
        depends_on:
          - cxi-hub-rabbitmq
        networks:
          default_hub:
        restart: unless-stopped
        logging:
          driver: json-file
          options:
            max-size: "512m"
            max-file: "5"

    cxi-hub-rabbitmq:
        container_name: cxi-hub-rabbitmq
        image: "gcr.io/mojix-registry/rabbitmq:4.1.9"
        hostname: "QAMOJIX-HUB01"
        environment:
          - digital_plateform_host=sprint.vizix.cloud
          - digital_plateform_port=18080
          - digital_plateform_protocol=http
          - digital_plateform_notification=sprint.vizix.cloud
          - amqps_cloud_server_port=50671
          - tenant_code=BAT
          - amqp_cloud_server_user=admin
          - amqp_cloud_server_pass=control123!
          - amqp_local_server_user=whiterabbit
          - amqp_local_server_pass=rabbit
        ports:
          - 15672:15672
          - 5672:5672
        volumes:
          - /data/hub/rabbitmq/storage:/var/lib/rabbitmq
        extra_hosts:
          - "sprint.vizix.cloud:10.128.0.64"
        networks:           
          default_hub:
        restart: unless-stopped
        logging:
          driver: json-file
          options:
            max-size: "512m"
            max-file: "5"

    cxi-hub-heartbeat:
        container_name: cxi-hub-heartbeat
        hostname: "QAMOJIX-HUB01"
        image: "gcr.io/mojix-registry/heartbeat:4.1.9"
        environment:
          - digital_plateform_protocol=http
          - digital_plateform_host=sprint.vizix.cloud
          - digital_plateform_port=18080
          - digital_plateform_user=BATroot
          - digital_plateform_pass=m0j1xInc!
          - amqps_cloud_server_port=50671
          - es_http_port=50673
          - tenant_code=BAT
          - premise_code=9999
          - digital_plateform_notification=sprint.vizix.cloud
          - amqp_local_server_host=cxi-hub-rabbitmq
          - amqp_local_server_management_port=15672
          - amqp_local_server_user=whiterabbit
          - amqp_local_server_pass=rabbit
          - tomcat_admin_user=tomcat
          - tomcat_admin_pass=tomcat
          - hub_apl_server_host=cxi-hub
          - hub_apl_server_port=8080
          - hub_hal_server_host=cxi-hub
          - hub_hal_server_port=8080
          - hub_hal_administration_server_host=cxi-hub
          - hub_hal_administration_server_port=8080
          - hub_printing_server_host=cxi-hub
          - hub_printing_server_port=8080
        volumes:
          - /data/hub/heartbeat/conf:/usr/share/heartbeat/conf:ro
          #Allows us to report on docker from the hosts information.
          - /var/run/docker.sock:/var/run/docker.sock
        extra_hosts:
          - "sprint.vizix.cloud:10.128.0.64"
        #command: heartbeat -e -d "publish" -strict.perms=false
        command: heartbeat -e -strict.perms=false
        networks:           
          default_hub:
        restart: unless-stopped
        logging:
          driver: json-file
          options:
            max-size: "512m"
            max-file: "5"

    cxi-hub-metricbeat:
        container_name: cxi-hub-metricbeat
        hostname: "QAMOJIX-HUB01"
        image: "gcr.io/mojix-registry/metricbeat:4.1.9"
        environment:
          - digital_plateform_protocol=http
          - digital_plateform_host=sprint.vizix.cloud
          - digital_plateform_port=18080
          - digital_plateform_notification=sprint.vizix.cloud
          - digital_plateform_user=BATroot
          - digital_plateform_pass=m0j1xInc!
          - es_http_port=50673
          - tenant_code=BAT
        volumes:
          # The commented sections below enable Metricbeat to monitor the Docker host rather than the Metricbeat container. These are used by the system m$
          - /proc:/hostfs/proc:ro
          - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
          #Allows us to report on docker from the hosts information
          - /var/run/docker.sock:/var/run/docker.sock
          #We mount the host filesystem so we can report on disk usage with the system module
          - /:/hostfs:ro
        #command: metricbeat -e -d "publish" -system.hostfs=/hostfs -strict.perms=false
        command: metricbeat -e -system.hostfs=/hostfs -strict.perms=false
        extra_hosts:
          - "sprint.vizix.cloud:10.128.0.64"
        networks:           
          default_hub:
        restart: unless-stopped
        logging:
          driver: json-file
          options:
            max-size: "512m"
            max-file: "5"

    cxi-hub-packetbeat:
        container_name: cxi-hub-packetbeat
        hostname: "QAMOJIX-HUB01"
        image: "gcr.io/mojix-registry/packetbeat:4.1.9"
        environment:
          - digital_plateform_protocol=http
          - digital_plateform_host=sprint.vizix.cloud
          - digital_plateform_port=18080
          - digital_plateform_notification=sprint.vizix.cloud
          - digital_plateform_user=BATroot
          - digital_plateform_pass=m0j1xInc!
          - es_http_port=50673
          - tenant_code=BAT
        #command: packetbeat -e -d "publish" -strict.perms=false
        command: packetbeat -e -strict.perms=false
        extra_hosts:
          - "sprint.vizix.cloud:10.128.0.64"
        # Packetbeat needs some elevated privileges to capture network traffic.
        # We'll grant them with POSIX capabilities.
        cap_add: ['NET_RAW', 'NET_ADMIN']
        # Use "host mode" networking to allow Packetbeat to capture traffic from
        # the real network interface on the host, rather than being isolated to the
        # container's virtual interface.
        network_mode: host
        restart: unless-stopped
        logging:
          driver: json-file
          options:
            max-size: "512m"
            max-file: "5"


    supply-process:
        container_name: supply-process
        image: "gcr.io/mojix-registry/supply-process:1.7.1"
        environment:
          - configuration.location.api.host=sprint.vizix.cloud
          - configuration.location.api.port=18080
          - configuration.location.api.use.https=false
          - supply.chain.api.use.https=false
          - supply.chain.api.port=80
          - tenant_code=BAT
          - logging.level.com.cxi=INFO
          - logging.level.root=INFO
          - server.servlet.contextPath=/supply-process/rest
          - server.context-path=/supply-process/rest
          - apl.api.host=cxi-hub
          - apl.api.port=8080
          - apl.api.war.name=apl-webservices
          - apl.api.connect.timeout=1000
          - apl.api.read.timeout=3000
          - epcis.hub.host=cxi-hub
          - epcis.hub.api.port=8080
          - epcis.hub.api.war.name=apl-webservices
          - epcis.hub.api.connect.timeout=1000
          - epcis.hub.api.read.timeout=3000
          - reader.gateway.api.host=reader-gateway
          - reader.gateway.api.port=8081
          - reader.gateway.api.war.name=readergateway
          - reader.gateway.api.connect.timeout=1000
          - reader.gateway.api.read.timeout=3000
          - reader.read.time.offset=0
          - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -XshowSettings:vm
          - supply.chain.api.host=hub-supply-chain-api
          - supply.chain.api.user=supplyChainAdmin
          - supply.chain.api.password=supplyChainAdmin
          - supply.chain.api.war.name=supply-chain-api
          - supply.chain.api.connect.timeout=1000
          - supply.chain.api.read.timeout=3000
          - supply.chain.api.devices.filterMode=AUTOMATED_PROCESS
          - configuration.location.api.user=BATroot
          - configuration.location.api.password=m0j1xInc!
          - product.api.host=product-api-local
          - product.api.port=8080
          - allowObjectEvent=true
          - allowTransactionEvent=true
          - filter.product.unknown=false
          - filter.product.cp=false
          - filter.reflist=false
          - filter.reflist.ttl.second=0
        ports:
          - 8082:80
        volumes:
          - /data/hub/tomcat/logs:/usr/local/supply-process/logs
        extra_hosts:
          - "sprint.vizix.cloud:10.128.0.64"
        depends_on:
          - cxi-hub
          - reader-gateway
          - product-api-local
        networks:           
          default_hub:
        restart: unless-stopped
        logging:
          driver: json-file
          options:
            max-size: "512m"
            max-file: "5"

    reader-gateway:
        container_name: reader-gateway
        image: "gcr.io/mojix-registry/reader-gateway:1.1.8"
        environment:
          - logging.level.com.cxi=INFO
          - logging.level.root=INFO
          - logging.path=/usr/local/reader-gateway
          - logging.file=reader-gateway.log
          - hal.url=http://cxi-hub:8080/hal-webservices/
          - server.port=8081
          - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2  -XshowSettings:vm -Dio.netty.allocator.useCacheForAllThreads=false
          - spring.data.mongodb.database=tagState
          - spring.data.mongodb.host=mongodb
          - spring.data.mongodb.port=27017
          - reader.gateway.cache.document.size=10000
        ports:
            - 8081:8081
        depends_on:
            - cxi-hub
            - mongodb
        networks:           
                default_hub:
        restart: unless-stopped
        logging:
            driver: json-file
            options:
                max-size: "512m"
                max-file: "5"

    mongodb:
        image: mongo
        ports:
          - 27017:27017
        networks:           
          default_hub:
        environment:
          - MONGO_INITDB_DATABASE=tagState
        restart: unless-stopped

    sync-manager:
        container_name: sync-manager
        image: "gcr.io/mojix-registry/hub-sync-manager:1.0.9"
        ports:
          - 8085:8080
        environment:
          - hub.configuration.server.host=sprint.vizix.cloud:18080
          - hub.configuration.server.scheme=http
          - api.supplychain.remote.uri=http://BATroot:m0j1xInc!@sprint.vizix.cloud:18080/supply-chain-api
          - api.product.remote.uri=http://BATroot:m0j1xInc!@sprint.vizix.cloud:18080/product-api
          - hub.name=QAMOJIX-HUB01
          - master.configuration.login=void
          - master.configuration.password=void
          - hub.configuration.filepath=/usr/local/tomcat/tagsys
          - api.supplychain.local.uri=http://hub-supply-chain-api:80/supply-chain-api
          - sync.supplychain.batch.size=500
          - api.product.local.uri=http://product-api-local:8080/product-api
          - sync.product.push.thread.size=1
          - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1  -XshowSettings:vm
        extra_hosts:
          - "sprint.vizix.cloud:10.128.0.64"
        networks:           
          default_hub:
        restart: unless-stopped
        depends_on:
          - product-api-local

    product-api-local:
        container_name: product-api-local
        image: "gcr.io/mojix-registry/product-api:1.8.5"
        ports:
          - 8086:8080
        environment:
          images-repository-path: .
          max-amount-product-returned: 500
          JAVA_OPTS: '-Djdbc-username=productAdmin -Djdbc-password=productAdmin -Djdbc-url=product-api-local-db -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1  -XshowSettings:vm'
        depends_on:
          product-api-local-db:
            condition: service_healthy
        networks:           
          default_hub:
        restart: unless-stopped

    product-api-local-db:
        container_name: product-api-local-db
        image: mysql:5.7.22
        ports:
            - "3307:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=businessProducts
          - MYSQL_USER=productAdmin
          - MYSQL_PASSWORD=productAdmin
        volumes:
          - /data/hub/product-api-local-db/mysqlproduct.cnf:/etc/mysql/conf.d/mysqlproduct.cnf
          - /data/hub/product-api-local-db-data:/var/lib/mysql
        healthcheck:
          test: mysqladmin -uroot -proot ping
          interval: 15s
          timeout: 10s
          retries: 4
          start_period: 30s
        networks:
          default_hub:
        restart: unless-stopped

    hub-documents-ingestion:
        container_name: hub-documents-ingestion
        image: "gcr.io/mojix-registry/hub-documents-ingestion:4.1.0"
        environment:
          - amqp.host=10.128.0.64
          - amqp.port=5672
          - amqp.user=admin
          - amqp.password=control123!
          - amqp.qos.nb=10
          - api.configuration.locations.uri=http://BATroot:m0j1xInc!@sprint.vizix.cloud:18080/statemachine-api-configuration
          - api.configuration.devices.uri=http://BATroot:m0j1xInc!@sprint.vizix.cloud:18080/statemachine-api-configuration
          - hub.code=QAMOJIX-HUB01
          - tenant.code=BAT
          - api.supplychain.uri=http://hub-supply-chain-api:80/supply-chain-api
          - api.supplychain.timeout.ms=10000
          - api.supplychain.failure.max=5
          - api.supplychain.reset.timeout.ms=30000
          - api.supplychain.retry.max=0
          - api.configuration.timeout.ms=10000
          - api.configuration.reset.timeout.ms=30000
        ports:
          - 8083:8080
        extra_hosts:
          - "sprint.vizix.cloud:10.128.0.64"
        depends_on:
          - hub-supply-chain-api
        networks:           
          default_hub:
        restart: unless-stopped
        logging:
          driver: json-file
          options:
            max-size: "512m"
            max-file: "5"

    hub-supply-chain-api:
        container_name: hub-supply-chain-api
        image: "gcr.io/mojix-registry/hub-supply-chain-api:1.0.3"
        environment:
          - configuration.location.scheme=http
          - configuration.location.host=sprint.vizix.cloud
          - configuration.location.port=18080
          - logging.level.com.cxi=INFO
          - logging.level.root=INFO
          - server.servlet.contextPath=/supply-chain-api
          - spring.datasource.name=supplyChainDataSource
          - spring.datasource.url=jdbc:mysql://hub-supply-chain-api-db:3306/supplyChain?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true
          - spring.datasource.username=supplyChainAdmin
          - spring.datasource.password=supplyChainAdmin
          - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1  -XshowSettings:vm
          - hub.code=QAMOJIX-HUB01
          - configuration.location.war=statemachine-api-configuration
          - configuration.location.user=BATroot
          - configuration.location.password=m0j1xInc!
        ports:
          - 8084:80
        extra_hosts:
          - "sprint.vizix.cloud:10.128.0.64"
        depends_on:
          hub-supply-chain-api-db:
            condition: service_healthy
        networks:           
          default_hub:
        restart: unless-stopped
        logging:
          driver: json-file
          options:
            max-size: "512m"
            max-file: "5"

    hub-supply-chain-api-db:
        container_name: hub-supply-chain-api-db
        image: mysql:5.7.22
        # Allow to connect with workbench
        ports:
          - "3306:3306"
        volumes:
          - /data/hub/supply-chain-api-db:/var/lib/mysql
          - /data/hub/supply-chain-api-db_conf/mysqlsupply.cnf:/etc/mysql/conf.d/mysqlsupply.cnf
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=supplyChain
          - MYSQL_USER=supplyChainAdmin
          - MYSQL_PASSWORD=supplyChainAdmin
        healthcheck:
          test: mysqladmin -uroot -proot ping
          interval: 15s
          timeout: 10s
          retries: 4
          start_period: 30s
        networks:           
          default_hub:
        restart: unless-stopped
        logging:
          driver: json-file
          options:
            max-size: "512m"
            max-file: "5"

    monitoring:
        hostname: monitoring
        container_name: monitoring
        image: "gcr.io/mojix-registry/edge-monitoring:v7.25.1"
        environment:
          - EDGE_MONITORING_READERGATEWAY_BASEURL=http://reader-gateway:8081
          - EDGE_MONITORING_PRINTING_BASEURL=http://cxi-hub:8080/printing
          - EDGE_MONITORING_PREMISE_CODE=9999
          - EDGE_MONITORING_PRIMARY_EDGE=True
          - EDGE_MONITORING_LOG_LEVEL=INFO
          - EDGE_MONITORING_PERIOD_SEC=30
          - EDGE_MONITORING_HEARTBEAT_PERIOD_SEC=30
          - EDGE_MONITORING_PROMETHEUS_PUSHGATEWAY_BASEURL=https://sprint.vizix.cloud/pushgateway
          - EDGE_MONITORING_PROMETHEUS_PUSHGATEWAY_USER=BATroot
          - EDGE_MONITORING_PROMETHEUS_PUSHGATEWAY_PASSWORD=m0j1xInc!
          - EDGE_MONITORING_CLOUD_HOST=sprint.vizix.cloud
          - EDGE_MONITORING_CLOUD_USERNAME=BATroot
          - EDGE_MONITORING_CLOUD_PASSWORD=m0j1xInc!
        extra_hosts:
          - "sprint.vizix.cloud:10.128.0.64"
        healthcheck:
          test: ["CMD-SHELL", "/app/healthcheck.sh"]
          interval: 60s
          timeout: 10s
          retries: 3
          start_period: 6s
        networks:           
          default_hub:
        restart: unless-stopped
        logging:
          driver: json-file
          options:
            max-size: "512m"
            max-file: "5"
networks:
  default_hub:
    external: true
