version: "3.5"

networks:
  default_hub:
    external: true

services:
  ytem-connector-sick-simulator:
    image: gcr.io/mojix-registry/ytem-connector-sick-simulator:main
    networks:
      - default_hub
    environment:
      - CONNECTOR_HOST=sick-connector
      - CONNECTOR_PORT=8765
      - RESULT_TIMER_PERIOD=15s
      - CHECK_TIMER_PERIOD=20s
      - HEARTBEAT_TIMER_PERIOD=15s
      - API_HOST=http://supply-chain-api:80
      - API_KEY=DUMMY
      - VERIFICATION_HOST=http://proxy
      - VERIFICATION_PORT=80
      - PRODUCT_API_HOST=http://product-api:8080
      - PRODUCT_API_KEY=DUMMY
    ports:
      - 8991:8080
