apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: qa-02-vizix-cloud
  labels:
    mojix.service: alerting-api
  name: alerting-api
spec:
  replicas: 1
  selector:
    matchLabels:
      mojix.service: alerting-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        mojix.service: alerting-api
    spec:
      containers:
      - name: alerting-api
        imagePullPolicy: "Always"
        image: mojix/alerting-api:v6.51.2
        env:
        - name: digital_plateform_port
          value: "18080"
        - name: configuration.api.host
          value: "internaltransformer"
        - name: es_http_port
          value: "9200"
        - name: amqp_ssl_port
          value: "5671"
        - name: configuration.api.port
          value: "8080"
        - name: configuration.api.war.name
          value: "statemachine-api-configuration"
        - name: metrics.elasticsearch.host
          value: "shopcx-elasticsearch-monitoring"
        - name: configuration.api.authorization
          value: "Basic cm9vdDpDb250cm9sMTIzIQ=="
        - name: alerting.multitenant.enabled
          value: "false"
        - name: JAVA_OPTS
          value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1  -XshowSettings:vm"
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
      hostname: alerting-api
      restartPolicy: Always
      imagePullSecrets:
        - name: mojix-registry

---
apiVersion: v1
kind: Service
metadata:
  namespace: qa-02-vizix-cloud
  labels:
    mojix.service: alerting-api
  name: alerting-api
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    mojix.service: alerting-api
status:
  loadBalancer: {}
