version: "3.5"

services:
  client:
    image: gcr.io/mojix-registry/kafka-secure-client:master
    environment:
      - KAFKA_SERVERS=red-at-edge.vizix.io:9293
      - KAFKA_TOPIC=___notifications___fittingrooms
      - KAFKA_CONSUMER_GROUP=KafkaSecureDEVOPS5
      - KAFKA_SECURITY_PROTOCOL=SSL
      - SSL_TRUSTSTORE_LOCATION=/home/gradle/build/kafka.truststore.jks
      - SSL_TRUSTSTORE_PASSWORD=control123!
      - SSL_KEYSTORE_LOCATION=/home/gradle/build/kafka.keystore.jks
      - SSL_KEYSTORE_PASSWORD=control123!
      - SSL_KEY_PASSWORD=control123!
    extra_hosts:
      - "red-dev-kafka:34.142.61.195"
    dns_search:
      - "vizix.io"
    volumes:
      - ./ks/kafka.truststore.jks:/home/gradle/build/kafka.truststore.jks
      - ./ks/kafka.keystore.jks:/home/gradle/build/kafka.keystore.jks
